package pojos;
// Generated 4/12/2012 04:02:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Deportes generated by hbm2java
 */
public class Deportes  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Torneos> torneoses = new HashSet<Torneos>(0);

    public Deportes() {
    }

	
    public Deportes(String nombre) {
        this.nombre = nombre;
    }
    public Deportes(String nombre, Set<Torneos> torneoses) {
       this.nombre = nombre;
       this.torneoses = torneoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Torneos> getTorneoses() {
        return this.torneoses;
    }
    
    public void setTorneoses(Set<Torneos> torneoses) {
        this.torneoses = torneoses;
    }




}


