package pojos;
// Generated 4/12/2012 04:02:37 PM by Hibernate Tools 3.2.1.GA



/**
 * EncuentroEquipo generated by hbm2java
 */
public class EncuentroEquipo  implements java.io.Serializable {


     private Integer id;
     private Encuentros encuentros;
     private Equipos equipos;

    public EncuentroEquipo() {
    }

    public EncuentroEquipo(Encuentros encuentros, Equipos equipos) {
       this.encuentros = encuentros;
       this.equipos = equipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Encuentros getEncuentros() {
        return this.encuentros;
    }
    
    public void setEncuentros(Encuentros encuentros) {
        this.encuentros = encuentros;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }




}


