package pojos;
// Generated 4/12/2012 04:02:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Encuentros generated by hbm2java
 */
public class Encuentros  implements java.io.Serializable {


     private Integer id;
     private Torneos torneos;
     private String juez;
     private Date hora;
     private Date fecha;
     private String sede;
     private Set<EncuentroEquipo> encuentroEquipos = new HashSet<EncuentroEquipo>(0);

    public Encuentros() {
    }

	
    public Encuentros(Torneos torneos, Date hora, Date fecha) {
        this.torneos = torneos;
        this.hora = hora;
        this.fecha = fecha;
    }
    public Encuentros(Torneos torneos, String juez, Date hora, Date fecha, String sede, Set<EncuentroEquipo> encuentroEquipos) {
       this.torneos = torneos;
       this.juez = juez;
       this.hora = hora;
       this.fecha = fecha;
       this.sede = sede;
       this.encuentroEquipos = encuentroEquipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Torneos getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneos torneos) {
        this.torneos = torneos;
    }
    public String getJuez() {
        return this.juez;
    }
    
    public void setJuez(String juez) {
        this.juez = juez;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public Set<EncuentroEquipo> getEncuentroEquipos() {
        return this.encuentroEquipos;
    }
    
    public void setEncuentroEquipos(Set<EncuentroEquipo> encuentroEquipos) {
        this.encuentroEquipos = encuentroEquipos;
    }




}


