package pojos;
// Generated 2/12/2012 12:37:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String nombre;
     private int puntos;
     private boolean participando;
     private Set<RegistroUsuarioEquipo> registroUsuarioEquipos = new HashSet<RegistroUsuarioEquipo>(0);
     private Set<EncuentroEquipo> encuentroEquipos = new HashSet<EncuentroEquipo>(0);

    public Equipos() {
    }

	
    public Equipos(Usuario usuario, String nombre, int puntos, boolean participando) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.puntos = puntos;
        this.participando = participando;
    }
    public Equipos(Usuario usuario, String nombre, int puntos, boolean participando, Set<RegistroUsuarioEquipo> registroUsuarioEquipos, Set<EncuentroEquipo> encuentroEquipos) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.puntos = puntos;
       this.participando = participando;
       this.registroUsuarioEquipos = registroUsuarioEquipos;
       this.encuentroEquipos = encuentroEquipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(int puntos) {
        this.puntos = puntos;
    }
    public boolean isParticipando() {
        return this.participando;
    }
    
    public void setParticipando(boolean participando) {
        this.participando = participando;
    }
    public Set<RegistroUsuarioEquipo> getRegistroUsuarioEquipos() {
        return this.registroUsuarioEquipos;
    }
    
    public void setRegistroUsuarioEquipos(Set<RegistroUsuarioEquipo> registroUsuarioEquipos) {
        this.registroUsuarioEquipos = registroUsuarioEquipos;
    }
    public Set<EncuentroEquipo> getEncuentroEquipos() {
        return this.encuentroEquipos;
    }
    
    public void setEncuentroEquipos(Set<EncuentroEquipo> encuentroEquipos) {
        this.encuentroEquipos = encuentroEquipos;
    }




}


