package pojos;
// Generated 4/12/2012 04:02:37 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistroUsuarioEquipo generated by hbm2java
 */
public class RegistroUsuarioEquipo  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Equipos equipos;

    public RegistroUsuarioEquipo() {
    }

    public RegistroUsuarioEquipo(Usuario usuario, Equipos equipos) {
       this.usuario = usuario;
       this.equipos = equipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }




}


