package pojos;
// Generated 2/12/2012 12:37:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneos generated by hbm2java
 */
public class Torneos  implements java.io.Serializable {


     private Integer id;
     private String nomTorneo;
     private int capacidadEqui;
     private String desc;
     private String categoria;
     private Date fechaIni;
     private Date fechaFin;
     private int limiteEquipo;
     private Set<Encuentros> encuentroses = new HashSet<Encuentros>(0);

    public Torneos() {
    }

	
    public Torneos(String nomTorneo, int capacidadEqui, String desc, String categoria, Date fechaIni, Date fechaFin, int limiteEquipo) {
        this.nomTorneo = nomTorneo;
        this.capacidadEqui = capacidadEqui;
        this.desc = desc;
        this.categoria = categoria;
        this.fechaIni = fechaIni;
        this.fechaFin = fechaFin;
        this.limiteEquipo = limiteEquipo;
    }
    public Torneos(String nomTorneo, int capacidadEqui, String desc, String categoria, Date fechaIni, Date fechaFin, int limiteEquipo, Set<Encuentros> encuentroses) {
       this.nomTorneo = nomTorneo;
       this.capacidadEqui = capacidadEqui;
       this.desc = desc;
       this.categoria = categoria;
       this.fechaIni = fechaIni;
       this.fechaFin = fechaFin;
       this.limiteEquipo = limiteEquipo;
       this.encuentroses = encuentroses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomTorneo() {
        return this.nomTorneo;
    }
    
    public void setNomTorneo(String nomTorneo) {
        this.nomTorneo = nomTorneo;
    }
    public int getCapacidadEqui() {
        return this.capacidadEqui;
    }
    
    public void setCapacidadEqui(int capacidadEqui) {
        this.capacidadEqui = capacidadEqui;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getLimiteEquipo() {
        return this.limiteEquipo;
    }
    
    public void setLimiteEquipo(int limiteEquipo) {
        this.limiteEquipo = limiteEquipo;
    }
    public Set<Encuentros> getEncuentroses() {
        return this.encuentroses;
    }
    
    public void setEncuentroses(Set<Encuentros> encuentroses) {
        this.encuentroses = encuentroses;
    }




}


