package pojos;
// Generated 4/12/2012 04:02:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private int username;
     private int privilegios;
     private String password;
     private String nombre;
     private Set<RegistroUsuarioEquipo> registroUsuarioEquipos = new HashSet<RegistroUsuarioEquipo>(0);
     private Set<Equipos> equiposes = new HashSet<Equipos>(0);

    public Usuario() {
    }

	
    public Usuario(int username, int privilegios, String password, String nombre) {
        this.username = username;
        this.privilegios = privilegios;
        this.password = password;
        this.nombre = nombre;
    }
    public Usuario(int username, int privilegios, String password, String nombre, Set<RegistroUsuarioEquipo> registroUsuarioEquipos, Set<Equipos> equiposes) {
       this.username = username;
       this.privilegios = privilegios;
       this.password = password;
       this.nombre = nombre;
       this.registroUsuarioEquipos = registroUsuarioEquipos;
       this.equiposes = equiposes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUsername() {
        return this.username;
    }
    
    public void setUsername(int username) {
        this.username = username;
    }
    public int getPrivilegios() {
        return this.privilegios;
    }
    
    public void setPrivilegios(int privilegios) {
        this.privilegios = privilegios;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<RegistroUsuarioEquipo> getRegistroUsuarioEquipos() {
        return this.registroUsuarioEquipos;
    }
    
    public void setRegistroUsuarioEquipos(Set<RegistroUsuarioEquipo> registroUsuarioEquipos) {
        this.registroUsuarioEquipos = registroUsuarioEquipos;
    }
    public Set<Equipos> getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set<Equipos> equiposes) {
        this.equiposes = equiposes;
    }




}


